name: Build and Deploy to Azure

on:
  push:
    branches:
      - dev  # Set the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.204'  # Adjust to your .NET version

    - name: Restore dependencies
      run: dotnet restore src/CulturNary/CulturNary.Web/CulturNary.Web.csproj

    - name: Build
      run: dotnet build src/CulturNary/CulturNary.Web/CulturNary.Web.csproj --configuration Release --no-restore

    - name: Restore dependencies for test project
      run: dotnet restore src/CulturNary/CulturNary.Test/CulturNary.Test.csproj

    - name: Test
      run: dotnet test src/CulturNary/CulturNary.Test/CulturNary.Test.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish src/CulturNary/CulturNary.Web/CulturNary.Web.csproj --configuration Release --no-build -o ./publish

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CulturNary'  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
